only build windows

diff --git a/.github/workflows/java-publish.yml b/.github/workflows/java-publish.yml
--- a/.github/workflows/java-publish.yml
+++ b/.github/workflows/java-publish.yml
@@ -28,124 +28,124 @@ permissions:
   contents: read
 
 jobs:
-  build-linux:
-    name: Build on Linux ${{ matrix.arch }}
-    runs-on: ${{ matrix.runner }}
-    timeout-minutes: 60
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - arch: x86-64
-            runner: ubuntu-24.04
-            docker_platform: linux/amd64
-            protoc_arch: x86_64
-            artifact: liblance_jni_linux_x86_64.zip
-          - arch: arm64
-            runner: ubuntu-24.04-arm64-8x
-            docker_platform: linux/arm64
-            protoc_arch: aarch_64
-            artifact: liblance_jni_linux_arm_64.zip
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
-        with:
-          ref: ${{ inputs.ref || github.ref }}
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
-      - name: Check glibc version outside docker
-        run: ldd --version
-      - name: Build and run in Debian 10 container
-        run: |
-          docker run --platform ${{ matrix.docker_platform }} -v ${{ github.workspace }}:/workspace -w /workspace debian:10 bash -c "
-
-            set -ex
-            # Update sources.list to use archive repositories for Debian 10 (EOL)
-            echo 'deb http://archive.debian.org/debian/ buster main' > /etc/apt/sources.list
-            echo 'deb http://archive.debian.org/debian-security buster/updates main' >> /etc/apt/sources.list
-            echo 'deb http://archive.debian.org/debian/ buster-updates main' >> /etc/apt/sources.list
-            apt-get update
-
-            DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --assume-yes \
-              apt-transport-https \
-              ca-certificates \
-              curl \
-              gpg \
-              bash \
-              less \
-              openssl \
-              libssl-dev \
-              pkg-config \
-              libsqlite3-dev \
-              libsqlite3-0 \
-              libreadline-dev \
-              git \
-              cmake \
-              dh-autoreconf \
-              clang \
-              g++ \
-              libc++-dev \
-              libc++abi-dev \
-              libprotobuf-dev \
-              libncurses5-dev \
-              libncursesw5-dev \
-              libudev-dev \
-              libhidapi-dev \
-              zip \
-              unzip
-
-            # https://github.com/databendlabs/databend/issues/8035
-            PROTOC_ZIP=protoc-3.15.0-linux-${{ matrix.protoc_arch }}.zip
-            curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.15.0/\$PROTOC_ZIP
-            unzip -o \$PROTOC_ZIP -d /usr/local
-            rm -f \$PROTOC_ZIP
-            protoc --version
-
-            curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
-            source \$HOME/.cargo/env
-            cargo --version
-
-            cd java/lance-jni
-
-            # https://github.com/rustls/rustls/issues/1967
-            export CC=clang
-            export CXX=clang++
-            ldd --version
-
-            cargo build --release --locked
-          "
-      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
-        with:
-          name: ${{ matrix.artifact }}
-          path: java/lance-jni/target/release/liblance_jni.so
-          retention-days: 1
-          if-no-files-found: error
-  build-macos:
-    name: Build on MacOS Arm64
-    runs-on: warp-macos-14-arm64-6x
-    timeout-minutes: 60
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
-        with:
-          ref: ${{ inputs.ref || github.ref }}
-      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2
-      - uses: Homebrew/actions/setup-homebrew@50b8c2ab4a835c38897ed2c56c293b07167c0b59 # master 2026-03-07
-      - name: Install dependencies
-        run: brew install protobuf
-      - name: Build native lib
-        working-directory: java/lance-jni
-        run: cargo build --release --locked
-      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
-        with:
-          name: liblance_jni_darwin_aarch64.zip
-          path: java/lance-jni/target/release/liblance_jni.dylib
-          retention-days: 1
-          if-no-files-found: error
+#  build-linux:
+#    name: Build on Linux ${{ matrix.arch }}
+#    runs-on: ${{ matrix.runner }}
+#    timeout-minutes: 60
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        include:
+#          - arch: x86-64
+#            runner: ubuntu-24.04
+#            docker_platform: linux/amd64
+#            protoc_arch: x86_64
+#            artifact: liblance_jni_linux_x86_64.zip
+#          - arch: arm64
+#            runner: ubuntu-24.04-arm64-8x
+#            docker_platform: linux/arm64
+#            protoc_arch: aarch_64
+#            artifact: liblance_jni_linux_arm_64.zip
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
+#        with:
+#          ref: ${{ inputs.ref || github.ref }}
+#      - name: Set up Docker Buildx
+#        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
+#      - name: Check glibc version outside docker
+#        run: ldd --version
+#      - name: Build and run in Debian 10 container
+#        run: |
+#          docker run --platform ${{ matrix.docker_platform }} -v ${{ github.workspace }}:/workspace -w /workspace debian:10 bash -c "
+#
+#            set -ex
+#            # Update sources.list to use archive repositories for Debian 10 (EOL)
+#            echo 'deb http://archive.debian.org/debian/ buster main' > /etc/apt/sources.list
+#            echo 'deb http://archive.debian.org/debian-security buster/updates main' >> /etc/apt/sources.list
+#            echo 'deb http://archive.debian.org/debian/ buster-updates main' >> /etc/apt/sources.list
+#            apt-get update
+#
+#            DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --assume-yes \
+#              apt-transport-https \
+#              ca-certificates \
+#              curl \
+#              gpg \
+#              bash \
+#              less \
+#              openssl \
+#              libssl-dev \
+#              pkg-config \
+#              libsqlite3-dev \
+#              libsqlite3-0 \
+#              libreadline-dev \
+#              git \
+#              cmake \
+#              dh-autoreconf \
+#              clang \
+#              g++ \
+#              libc++-dev \
+#              libc++abi-dev \
+#              libprotobuf-dev \
+#              libncurses5-dev \
+#              libncursesw5-dev \
+#              libudev-dev \
+#              libhidapi-dev \
+#              zip \
+#              unzip
+#
+#            # https://github.com/databendlabs/databend/issues/8035
+#            PROTOC_ZIP=protoc-3.15.0-linux-${{ matrix.protoc_arch }}.zip
+#            curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.15.0/\$PROTOC_ZIP
+#            unzip -o \$PROTOC_ZIP -d /usr/local
+#            rm -f \$PROTOC_ZIP
+#            protoc --version
+#
+#            curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
+#            source \$HOME/.cargo/env
+#            cargo --version
+#
+#            cd java/lance-jni
+#
+#            # https://github.com/rustls/rustls/issues/1967
+#            export CC=clang
+#            export CXX=clang++
+#            ldd --version
+#
+#            cargo build --release --locked
+#          "
+#      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
+#        with:
+#          name: ${{ matrix.artifact }}
+#          path: java/lance-jni/target/release/liblance_jni.so
+#          retention-days: 1
+#          if-no-files-found: error
+#  build-macos:
+#    name: Build on MacOS Arm64
+#    runs-on: warp-macos-14-arm64-6x
+#    timeout-minutes: 60
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
+#        with:
+#          ref: ${{ inputs.ref || github.ref }}
+#      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2
+#      - uses: Homebrew/actions/setup-homebrew@50b8c2ab4a835c38897ed2c56c293b07167c0b59 # master 2026-03-07
+#      - name: Install dependencies
+#        run: brew install protobuf
+#      - name: Build native lib
+#        working-directory: java/lance-jni
+#        run: cargo build --release --locked
+#      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
+#        with:
+#          name: liblance_jni_darwin_aarch64.zip
+#          path: java/lance-jni/target/release/liblance_jni.dylib
+#          retention-days: 1
+#          if-no-files-found: error
   build-windows:
     name: Build on Windows x86-64
     runs-on: windows-latest
-    timeout-minutes: 60
+    timeout-minutes: 600
     steps:
       - name: Checkout repository
         uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
@@ -168,8 +168,8 @@ jobs:
     runs-on: ubuntu-latest
     timeout-minutes: 30
     needs:
-      - build-linux
-      - build-macos
+#      - build-linux
+#      - build-macos
       - build-windows
     steps:
       - name: Checkout repository
